project_id = "mblnaviicbbxtxpbptnn"

[functions.send-quotation-notification]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.send-contact-reply]
verify_jwt = false

[functions.delete-user]
verify_jwt = false