project_id = "mblnaviicbbxtxpbptnn"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.delete-user]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-chat-notification]
    verify_jwt = false
  [functions.send-contact-reply]
    verify_jwt = false
  [functions.send-quotation-notification]
    verify_jwt = false
  [functions.submit-contact]
    verify_jwt = false
