
-- Add address columns to quotations table for Google Maps integration
ALTER TABLE public.quotations
  ADD COLUMN IF NOT EXISTS address_formatted TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS place_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS city TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS province TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS postal_code TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS country TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS address_components JSONB DEFAULT NULL;
